package com.tradinggate.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.provider.Settings;import android.view.*;import android.widget.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.Locale;

public class MainActivity extends Activity{
 static final String MT5="net.metaquotes.metatrader5", PREF="gate"; static final long UNLOCK=15*60*1000L; android.content.SharedPreferences p; TextView status,reason,timer; Button unlock,mt5; EditText news,entry,tp,sl; RadioButton busy,tired; CheckBox h4,h2,h1,liq,cisd,bos,idm; CountDownTimer cd;
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(0,dp(5),0,dp(5));return v;} CheckBox c(String s){CheckBox x=new CheckBox(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(16);return x;} EditText in(String s){EditText e=new EditText(this);e.setHint(s);e.setHintTextColor(Color.GRAY);e.setTextColor(Color.WHITE);e.setTextSize(16);e.setSingleLine();e.setPadding(dp(10),dp(6),dp(10),dp(6));e.setBackgroundColor(Color.rgb(28,28,28));return e;}
 TextView sec(String s){TextView v=t(s,18);v.setTypeface(null,1);v.setPadding(0,dp(18),0,dp(6));return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences(PREF,0);build();restore();}
 void build(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.BLACK);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(28));TextView title=t("🌸  TRADING GATE",25);title.setTypeface(null,1);title.setGravity(17);r.addView(title);TextView sub=t("Entry hanya kalau checklist lengkap.",13);sub.setTextColor(Color.GRAY);sub.setGravity(17);r.addView(sub);status=t("STATUS: TERKUNCI",18);status.setGravity(17);status.setTypeface(null,1);r.addView(status);timer=t("",14);timer.setGravity(17);timer.setTextColor(Color.GREEN);r.addView(timer);reason=t("",13);reason.setGravity(17);reason.setTextColor(Color.RED);r.addView(reason);
 r.addView(sec("1–2. KONDISI DIRI"));LinearLayout self=new LinearLayout(this);self.setOrientation(LinearLayout.VERTICAL);self.addView(t("Apakah saya sedang sibuk / ada kerjaan lain?",15));RadioGroup g1=new RadioGroup(this);RadioButton nb=new RadioButton(this);nb.setText("TIDAK — saya fokus");busy=new RadioButton(this);busy.setText("YA — saya sedang sibuk");g1.addView(nb);g1.addView(busy);nb.setTextColor(Color.WHITE);busy.setTextColor(Color.WHITE);nb.setChecked(true);self.addView(g1);self.addView(t("Apakah saya sedang capek / emosi?",15));RadioGroup g2=new RadioGroup(this);RadioButton nt=new RadioButton(this);nt.setText("TIDAK — kondisi stabil");tired=new RadioButton(this);tired.setText("YA — capek / emosi");g2.addView(nt);g2.addView(tired);nt.setTextColor(Color.WHITE);tired.setTextColor(Color.WHITE);nt.setChecked(true);self.addView(g2);r.addView(self);
 r.addView(sec("3–5. ZONA HTF"));h4=c("ZONA H4 sudah jelas");h2=c("ZONA H2 sudah jelas");h1=c("ZONA H1 sudah jelas");r.addView(h4);r.addView(h2);r.addView(h1);
 r.addView(sec("6. NEWS BESAR"));r.addView(t("Isi jam news besar dalam WITA. Gate mulai boleh dibuka 2 jam sebelum news sampai waktu news.",14));news=in("Contoh: 20:30");r.addView(news);TextView now=t("Waktu WITA sekarang: —",13);now.setTextColor(Color.GRAY);r.addView(now);
 r.addView(sec("7–10. KONFIRMASI MARKET"));liq=c("LIQUIDITY ✓");cisd=c("CISD ✓");bos=c("BOS ✓");idm=c("IDM ✓");r.addView(liq);r.addView(cisd);r.addView(bos);r.addView(idm);
 r.addView(sec("11–13. PLAN ENTRY"));r.addView(t("Plan Entry",14));entry=in("Contoh: Sell setelah CISD di POI H1");r.addView(entry);r.addView(t("TP",14));tp=in("Contoh: target harga / pip");r.addView(tp);r.addView(t("SL",14));sl=in("Contoh: invalidasi harga / pip");r.addView(sl);
 unlock=new Button(this);unlock.setText("🔒  CEK & UNLOCK MT5");unlock.setOnClickListener(v->checkUnlock());r.addView(unlock,new LinearLayout.LayoutParams(-1,dp(55)));mt5=new Button(this);mt5.setText("BUKA MT5");mt5.setEnabled(false);mt5.setOnClickListener(v->open());r.addView(mt5,new LinearLayout.LayoutParams(-1,dp(55)));Button a=new Button(this);a.setText("⚙ AKTIFKAN APP LOCK");a.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));r.addView(a,new LinearLayout.LayoutParams(-1,dp(48)));TextView n=t("Aktifkan Trading Gate di Pengaturan > Aksesibilitas agar MT5 yang dibuka langsung ikut ditahan saat gate terkunci.",12);n.setTextColor(Color.GRAY);r.addView(n);sv.addView(r);setContentView(sv);updateNow(now);}
 void updateNow(TextView v){ZonedDateTime z=ZonedDateTime.now(ZoneId.of("Asia/Makassar"));v.setText("Waktu WITA sekarang: "+z.format(DateTimeFormatter.ofPattern("HH:mm:ss")));}
 String validate(){if(busy.isChecked())return"LOCK: kamu sedang sibuk.";if(tired.isChecked())return"LOCK: kamu sedang capek / emosi.";if(!h4.isChecked()||!h2.isChecked()||!h1.isChecked())return"LOCK: zona H4, H2, H1 harus jelas.";if(!liq.isChecked())return"LOCK: Liquidity belum dikonfirmasi.";if(!cisd.isChecked())return"LOCK: CISD belum dikonfirmasi.";if(!bos.isChecked())return"LOCK: BOS belum dikonfirmasi.";if(!idm.isChecked())return"LOCK: IDM belum dikonfirmasi.";if(entry.getText().toString().trim().isEmpty())return"LOCK: Plan Entry wajib diisi.";if(tp.getText().toString().trim().isEmpty())return"LOCK: TP wajib diisi.";if(sl.getText().toString().trim().isEmpty())return"LOCK: SL wajib diisi.";String s=news.getText().toString().trim();if(!s.matches("\d{2}:\d{2}"))return"LOCK: isi jam News Besar, format HH:mm WITA.";int h=Integer.parseInt(s.substring(0,2)),m=Integer.parseInt(s.substring(3));if(h>23||m>59)return"LOCK: jam news tidak valid.";ZonedDateTime now=ZonedDateTime.now(ZoneId.of("Asia/Makassar")),nw=ZonedDateTime.of(now.toLocalDate(),LocalTime.of(h,m),ZoneId.of("Asia/Makassar"));if(now.isBefore(nw.minusHours(2)))return"LOCK: belum masuk window 2 jam sebelum news.";if(now.isAfter(nw))return"LOCK: waktu news sudah lewat.";return null;}
 void checkUnlock(){String e=validate();if(e!=null){status.setText("STATUS: TERKUNCI");status.setTextColor(Color.RED);reason.setText(e);mt5.setEnabled(false);return;}p.edit().putBoolean("unlocked",true).putLong("until",System.currentTimeMillis()+UNLOCK).apply();status.setText("STATUS: TERBUKA");status.setTextColor(Color.GREEN);reason.setText("Checklist lolos. Gate aktif 15 menit.");mt5.setEnabled(true);unlock.setText("✓ GATE TERBUKA");startTimer();}
 void startTimer(){if(cd!=null)cd.cancel();long left=p.getLong("until",0)-System.currentTimeMillis();if(left<=0){lock();return;}cd=new CountDownTimer(left,1000){public void onTick(long x){timer.setText(String.format(Locale.US,"MT5 terbuka: %02d:%02d",x/60000,(x/1000)%60));}public void onFinish(){lock();}}.start();}
 void lock(){p.edit().putBoolean("unlocked",false).putLong("until",0).apply();status.setText("STATUS: TERKUNCI");status.setTextColor(Color.RED);timer.setText("");reason.setText("Waktu habis. Checklist harus diulang.");mt5.setEnabled(false);unlock.setText("🔒  CEK & UNLOCK MT5");if(h4!=null){h4.setChecked(false);h2.setChecked(false);h1.setChecked(false);liq.setChecked(false);cisd.setChecked(false);bos.setChecked(false);idm.setChecked(false);entry.setText("");tp.setText("");sl.setText("");}}
 void restore(){if(p.getBoolean("unlocked",false)&&p.getLong("until",0)>System.currentTimeMillis()){status.setText("STATUS: TERBUKA");status.setTextColor(Color.GREEN);mt5.setEnabled(true);unlock.setText("✓ GATE TERBUKA");startTimer();}else lock();}
 void open(){Intent i=getPackageManager().getLaunchIntentForPackage(MT5);if(i!=null)startActivity(i);else Toast.makeText(this,"MT5 tidak ditemukan di HP.",Toast.LENGTH_LONG).show();}
}
